#! /bin/bash
cp ~/.config/cava/config .config/cava
cp ~/.config/compton.conf .config
cp ~/.config/conky/conky.conf .config/conky
cp ~/.config/i3/config .config/i3
cp ~/.config/mpd/mpd.conf .config/mpd
cp ~/.config/ranger/rc.conf .config/ranger
cp ~/.config/youtube-dl/config .config/youtube-dl
cp ~/.i3status.conf .
cp ~/.ncmpcpp/config .ncmpcpp
cp ~/.vimrc .
cp ~/.Xresources .
cp ~/.zshrc .
cp ~/.tmux.conf .
cp ~/.config/starship.toml .config/
cp ~/.local/bin/add-volume .local/bin/
cp ~/.local/bin/subtract-volume .local/bin/
cp ~/.local/bin/tla .local/bin/
cp ~/.local/bin/toggle-mute .local/bin/
