# Don't print a new line at the start of the prompt
add_newline = false

[aws]
disabled = true

[kubernetes]
disabled = false

[cmd_duration]
disabled = true

[rust]
symbol = "⚙️ "

[line_break]
disabled = false

[package]
symbol = "@ "

[time]
disabled = false
format = "[%F@%T]"
